import type { ContactNode, ContactConnection } from "../types";

export const mockContacts: ContactNode[] = [
  {
    id: "contact-1",
    accountId: "acct-1",
    firstName: "Sarah",
    lastName: "Chen",
    title: "Chief Technology Officer",
    department: "Executive Leadership",
    email: "sarah.chen@acme-corp.com",
    phone: "+1-555-0101",
    buyingRoles: ["economic_buyer"],
    sentiment: "positive",
    relationshipStrength: "strong",
    influenceLevel: "high",
    relationshipOwner: "John Smith",
    notes: "Key decision maker. Championed our last deal. Interested in AI capabilities.",
    lastContactedAt: "2025-12-15T10:00:00Z",
    positionX: 400,
    positionY: 50,
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-12-15T10:00:00Z",
  },
  {
    id: "contact-2",
    accountId: "acct-1",
    firstName: "Michael",
    lastName: "Torres",
    title: "VP of Engineering",
    department: "Engineering",
    email: "michael.torres@acme-corp.com",
    phone: "+1-555-0102",
    buyingRoles: ["champion", "technical_evaluator"],
    sentiment: "positive",
    relationshipStrength: "strong",
    influenceLevel: "high",
    relationshipOwner: "John Smith",
    notes: "Strong champion. Drove technical evaluation. Direct report to CTO.",
    lastContactedAt: "2025-12-20T14:00:00Z",
    positionX: 200,
    positionY: 200,
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-12-20T14:00:00Z",
  },
  {
    id: "contact-3",
    accountId: "acct-1",
    firstName: "Lisa",
    lastName: "Park",
    title: "VP of Product",
    department: "Product",
    email: "lisa.park@acme-corp.com",
    buyingRoles: ["influencer"],
    sentiment: "neutral",
    relationshipStrength: "moderate",
    influenceLevel: "medium",
    relationshipOwner: "Emily Davis",
    notes: "Needs more engagement. Could become a champion with the right use cases.",
    positionX: 600,
    positionY: 200,
    createdAt: "2025-02-15T08:00:00Z",
    updatedAt: "2025-11-10T09:00:00Z",
  },
  {
    id: "contact-4",
    accountId: "acct-1",
    firstName: "David",
    lastName: "Kumar",
    title: "Director of Infrastructure",
    department: "Engineering",
    email: "david.kumar@acme-corp.com",
    buyingRoles: ["technical_evaluator"],
    sentiment: "negative",
    relationshipStrength: "weak",
    influenceLevel: "medium",
    relationshipOwner: "John Smith",
    notes: "Concerned about migration complexity. Had bad experience with competitor. Needs reassurance.",
    positionX: 100,
    positionY: 380,
    createdAt: "2025-03-20T08:00:00Z",
    updatedAt: "2025-12-01T11:00:00Z",
  },
  {
    id: "contact-5",
    accountId: "acct-1",
    firstName: "Rachel",
    lastName: "Williams",
    title: "CFO",
    department: "Finance",
    email: "rachel.williams@acme-corp.com",
    buyingRoles: ["economic_buyer"],
    sentiment: "neutral",
    relationshipStrength: "weak",
    influenceLevel: "high",
    notes: "Controls budget. Have not established direct contact yet. Critical to engage.",
    positionX: 650,
    positionY: 50,
    createdAt: "2025-04-01T08:00:00Z",
    updatedAt: "2025-10-20T15:00:00Z",
  },
  {
    id: "contact-6",
    accountId: "acct-1",
    firstName: "James",
    lastName: "Novak",
    title: "Senior Security Architect",
    department: "Engineering",
    email: "james.novak@acme-corp.com",
    buyingRoles: ["blocker"],
    sentiment: "negative",
    relationshipStrength: "none",
    influenceLevel: "medium",
    notes: "Blocking procurement on security compliance grounds. Need to address SOC2 and GDPR concerns directly.",
    positionX: 300,
    positionY: 380,
    createdAt: "2025-05-10T08:00:00Z",
    updatedAt: "2025-12-05T16:00:00Z",
  },
  {
    id: "contact-7",
    accountId: "acct-1",
    firstName: "Angela",
    lastName: "Martinez",
    title: "Head of Data Science",
    department: "Data & Analytics",
    email: "angela.martinez@acme-corp.com",
    buyingRoles: ["end_user", "champion"],
    sentiment: "positive",
    relationshipStrength: "moderate",
    influenceLevel: "low",
    relationshipOwner: "Emily Davis",
    notes: "End user who loves the product. Good internal advocate but limited buying influence.",
    positionX: 500,
    positionY: 380,
    createdAt: "2025-06-15T08:00:00Z",
    updatedAt: "2025-12-18T13:00:00Z",
  },
];

export const mockConnections: ContactConnection[] = [
  {
    id: "conn-1",
    sourceContactId: "contact-2",
    targetContactId: "contact-1",
    connectionType: "reports_to",
    weight: 9,
    label: "Direct Report",
  },
  {
    id: "conn-2",
    sourceContactId: "contact-3",
    targetContactId: "contact-1",
    connectionType: "reports_to",
    weight: 9,
    label: "Direct Report",
  },
  {
    id: "conn-3",
    sourceContactId: "contact-4",
    targetContactId: "contact-2",
    connectionType: "reports_to",
    weight: 8,
    label: "Direct Report",
  },
  {
    id: "conn-4",
    sourceContactId: "contact-6",
    targetContactId: "contact-2",
    connectionType: "reports_to",
    weight: 7,
  },
  {
    id: "conn-5",
    sourceContactId: "contact-7",
    targetContactId: "contact-3",
    connectionType: "reports_to",
    weight: 7,
  },
  {
    id: "conn-6",
    sourceContactId: "contact-2",
    targetContactId: "contact-5",
    connectionType: "influences",
    weight: 6,
    label: "Budget Influence",
    notes: "Michael has strong credibility with the CFO on tech investments.",
  },
  {
    id: "conn-7",
    sourceContactId: "contact-6",
    targetContactId: "contact-4",
    connectionType: "influences",
    weight: 8,
    label: "Security Concerns",
    notes: "James heavily influences David's opinions on vendor selection.",
  },
  {
    id: "conn-8",
    sourceContactId: "contact-7",
    targetContactId: "contact-2",
    connectionType: "influences",
    weight: 5,
    label: "Use Case Advocacy",
  },
  {
    id: "conn-9",
    sourceContactId: "contact-6",
    targetContactId: "contact-1",
    connectionType: "blocks",
    weight: 7,
    label: "Security Veto",
    notes: "James has escalated security concerns directly to the CTO.",
  },
];
